name: Helm Composer
description: Renders HelmRelease CRD based on kustomize overlay structuress
runs:
  using: "composite"
  steps:

    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["internal/*.yaml"]'
      env:
        version: 3
        prcommit: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

    - run: |
        echo ${{ toJSON(github.event) }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rendered-helmreleases
        path: ./internal/
        retention-days: 90
