# This is a basic workflow to help you get started with Actions

name: print pull

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branc
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:

#       - uses: actions/checkout@v3

#       - uses: ./.github/actions/helm-deployer
#         with:
#           repository: flux-test
#           cluster: cluster01
#           namespace: namespacedemo
#           file: helm-release.yaml
#           token: ${{ secrets.FLUX_REPO_TOKEN }}
jobs:

  ci:
    runs-on: ubuntu-latest
    steps:

    - name: 'Print 4'
      uses: actions/github-script@v6
      with:
        retries: 3
        script: |

          const pr4 = await octokit.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: 4,
          });

          console.log(JSON.stringify(pr4.data))

    - name: 'Print 8'
      uses: actions/github-script@v6
      with:
        retries: 3
        script: |

          const pr8 = await octokit.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: 8,
          });

          console.log(JSON.stringify(pr8.data))
